### PR TITLE
Implement CRAI writing.

### PR DESCRIPTION
**Pull request by cmnbroad**
This PR implements CRAI index writing for .cram files, and enables it as the default for CRAM indexing. However, we may not want to reconsider changing the default given https://github.com/samtools/htsjdk/issues/531.

There are 2 commits since this is dependent on the refactoring that was in https://github.com/samtools/htsjdk/pull/510.

### CODE REVIEW

**Comment by droazen** [comment]
@vadimzalunin Can you review?

**Comment by droazen** [comment]
Recommend that we set the default back to `.bai` given open tickets like https://github.com/samtools/htsjdk/issues/531

**Comment by cmnbroad** [comment]
Agreed - reverted default index written for crams to .bai.

**Comment by vadimzalunin** [comment]
Seems fine to me. But we are going to need another PR to allow users to choose between BAI and CRAI.

PS
https://github.com/samtools/htsjdk/issues/531 can't be fixed other than default the counts in metadata.

**Comment by droazen** [comment]
Feel free to merge after making sure the default is still `bai`, and there are comments in the `crai` code explaining why the default is still `bai`.

**Comment by cmnbroad** [comment]
I'd prefer to hold off on merging this until https://github.com/samtools/htsjdk/pull/552 is merged, since that PR greatly expands the test coverage for cram index queries and  I'd like to run those tests against this code.

**Comment by yfarjoun** [comment]
blocked by #552

**Comment by cmnbroad** [comment]
This has been rebased and merged with #552, and a separate commit added that extends the new cram index query tests added in #552 to include analagous tests for crais generated using the code in this PR.

**Pull request merged**
