### PR TITLE
remove class Objects - JDK has a better version of it now

### PR DESCRIPTION
**Pull request by akiezun**
### Description

remove class Objects - JDK has a better version of it now.
Breaking change because clients may call to Objects. 

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by yfarjoun** [comment]
Can you explain how to get around the breaking change? Have you tried compiling picard or GATK4 with this change?

**Comment by akiezun** [comment]
Use the Jdk version

On Friday, June 3, 2016, Yossi Farjoun <notifications@github.com> wrote:

> Can you explain how to get around the breaking change? Have you tried
> compiling picard or GATK4 with this change?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/samtools/htsjdk/pull/633#issuecomment-223724765>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB5rL0FVat0d_wxP39UyvdgZmkm1hpJkks5qIMhCgaJpZM4Itui7>
> .
>


-- 
Sent from Gmail Mobile

**Comment by akiezun** [comment]
@droazen good to merge?

**Comment by droazen** [comment]
:+1: merge at will @akiezun

**Pull request merged**
