### PR TITLE
Yf intel deflator+unittest+sigsegv

### PR DESCRIPTION
**Pull request by yfarjoun**
### Description

Please explain the changes you made here.
Explain the **motivation** for making this change. What existing problem does the pull request solve?

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by yfarjoun** [comment]
while this seems to be passing in travis, the logs show a SIGSEGV:

 
   [testng] #
   [testng] # A fatal error has been detected by the Java Runtime Environment:
   [testng] #
   [testng] #  SIGSEGV (0xb) at pc=0x00007fb39309f854, pid=3330, tid=140409262946048
   [testng] #
   [testng] # JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
   [testng] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17 mixed mode linux-amd64 compressed oops)
   [testng] # Problematic frame:
   [testng] # V  [libjvm.so+0x89e854]  Metaspace::allocate(unsigned long, Metaspace::MetadataType)+0x14
   [testng] #
   [testng] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
   [testng] #
   [testng] # An error report file with more information is saved as:
   [testng] # /home/travis/build/samtools/htsjdk/hs_err_pid3330.log
   [testng] #
   [testng] # If you would like to submit a bug report, please visit:
   [testng] #   http://bugreport.java.com/bugreport/crash.jsp
   [testng] #

**Comment by yfarjoun** [comment]
@mishalinaik please see if you can make heads or tails from this.

**Comment by yfarjoun** [comment]
As I mentioned, it fails on our GenuineIntel machine, but succeeds on a AMD machine (both 64-bit)

**Comment by mishalinaik** [comment]
@yfarjoun Fixed the issue you were facing it was a tricky one. I pushed the commit

**Comment by yfarjoun** [comment]
@akiezun given that this is a different .so from what you originally tested, could you run your speed-up test on this commit and give it a speed-wise thumbs up? Ideally you would look at the difference between: 

- native jdkDeflator (version 8 is supposed to be faster than before, according to @tfenne)
- previous good version of intelDeflator
- this version of intelDeflator.

**Comment by yfarjoun** [comment]
@akiezun sorry, I mentioned this somewhere else, but it was probably unclear, could you run your speedup tests on this branch?

**Comment by akiezun** [comment]
Will do, sorry about the delay

**Comment by akiezun** [comment]
@yfarjoun do you want level 1 and 5 right?

**Comment by yfarjoun** [comment]
sure.

**Comment by akiezun** [comment]
new code (this branch). 
Linux 2.6.32-573.18.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132
(32GB of heap space), using BAM file of 1.6GB  on NFS.

level 5, JdkDeflater, SyncIO  Elapsed time 212.253 seconds  (baseline)
level 5, IntelDeflater, SyncIO Elapsed time 183.807 seconds  (1.15x  speedup over baseline) 
level 1, JdkDeflater, SyncIO  Elapsed time 135.901 seconds  (1.55x speedup over baseline)
level 1, IntelDeflater, SyncIO Elapsed time 83.993 seconds    (2.55x speedup over baseline)

for fun i looked at asyncIO too (only writing is implemented right now)
level 1, IntelDeflater, AsyncIO Elapsed time 80.150 seconds (2.6x speedup over baseline)

**Comment by akiezun** [comment]
master (same machine specs etc)
level 5, JdkDeflater, SyncIO  Elapsed time 208.985 seconds
level 5, IntelDeflater, SyncIO Elapsed time 165.721 seconds **<-- this line worried me (new code is slower?)** (2 more reruns of master 169.326, 176.811)
level 1, JdkDeflater, SyncIO  Elapsed time 138.908 seconds
level 1, IntelDeflater, SyncIO Elapsed time 118.816 seconds
level 1, IntelDeflater, AsyncIO Elapsed time 95.011 seconds

So level 1 looks great but level 5 is not so clear cut. To get a better picture, I reran this new branch level 5 IntelDeflater 3 more times:
167.046 seconds
167.476 seconds
168.618 seconds

**Performance Conclusion: performance wise this branch looks good (level 1 improved a lot).**

What I'm unsure about is that file sizes fluctuate:
initial file is 1673819016 bytes
master:
1673819015 mJdk.Level5.sync.bam  <-
1662517443 mIntel.Level5.sync.bam  <- why are those two different sizes (jdk vs intel)?
1899122247 mJdk.Level1.sync.bam   <-
1835785277 mIntel.Level1.sync.bam  <- why are those two different sizes (jdk vs intel)?
1835785277 mIntel.Level1.async.bam (good - same as sync)

new branch:
1673819015 yJdk.Level5.synch.bam <- same as master
1662517443 yIntel.Level5.sync.bam <- same as master
1899122247 yJdk.Level1.sync.bam  <- same as master
2148761044 yIntel.Level1.sync.bam  <- why is size different than jdk and different than master?
2148761044 yIntel.Level1.async.bam (good - same as sync)

@mishalinaik are those changes expected, ie different from JDKDeflater and different between 2 versions of IntelDeflater on level 1?

**Comment by mishalinaik** [comment]
@akiezun Yes, this is expected. The tradeoff with using igzip to compress at level 1 is you have much higher performance than standard zlib (at compression level 1) but with slightly lower compression ratio (its very close to zlib but not the same). Hope that helps

**Comment by yfarjoun** [comment]
So this is a PR joint work by myself and @mishalinaik. We need a review...

Given the headache that this recently caused, I propose it be @jacarey 

Anyone else care to chime in?

**Comment by akiezun** [comment]
@jacarey sounds right

**Comment by akiezun** [comment]
@yfarjoun how does the .so file in this PR relate to that that got merged in https://github.com/samtools/htsjdk/pull/539? is it the same, or newer or older (something else)?

**Comment by jacarey** [comment]
This look good to me. Thanks to everyone for their work on this.

**Comment by droazen** [comment]
@yfarjoun Can this be merged? What's the answer the @akiezun's question above ("how does the .so file in this PR relate to that that got merged in #539? is it the same, or newer or older (something else)?")

**Comment by yfarjoun** [comment]
This is the only .so version that should be considered to be not broken.

**Comment by yfarjoun** [comment]
it's the same .so but that one hasn't been merged into master...

**Comment by yfarjoun** [comment]
I'll squash, rebase and merge. thanks for the review and thanks @mishalinaik .

**Comment by yfarjoun** [comment]
actually, I'm not going to squash, just rebase since one commit is mine and the other one is @mishalinaik's

**Comment by yfarjoun** [comment]
will merge once tests pass.

**Comment by droazen** [comment]
@yfarjoun Tests have passed -- can this be merged?

**Comment by akiezun** [comment]
@jacarey @yfarjoun @droazen are we good to make a 2.0.2 release? it's been 4 months since 2.0.1 - i think this was the last blocking issue

**Comment by droazen** [comment]
@akiezun Erm, actually it's been exactly 1 month since the last release, which was `2.1.1`. This next release will be `2.2.0`, and yes we are go for launch.

**Comment by akiezun** [comment]
true, my bad - i looked at 'drafts'
cool, who presses the button? i think it's @jacarey

**Pull request merged**
