### PR TITLE
NPE bug fix from quering empty region & BED package refactoring

### PR DESCRIPTION
**Pull request by AlpenDitrix**
Inheritance at htsjdk.tribble.bed was a bit odd so I tried to fix this. 
Also simplified enum for Strand

A bit later I found and fixed a tiny bug in BinningIndexContext#query for regions berofe and after actual chomosome bounds. 

(I have success on my ow test, don't know why Travis fails. Trying to find out asap. Possibly because of corrupted line-endings)

### CODE REVIEW

**Comment by AlpenDitrix** [comment]
And one test Travis-job somewhy failed to load some dependencies after test succeed.

What's wrong with him? And can I try to rerun it without fake-committing?

**Comment by AlpenDitrix** [comment]
I've triggered rerun for 85b8574 commit in my-own-branch (my last commit in this merge d04c201) and obviously it all passed. 


https://travis-ci.org/AlpenDitrix/htsjdk/builds/77143916

**Comment by lbergelson** [comment]
Hi.  I've triggered a manual rebuild on the failing test.

**Comment by yfarjoun** [comment]
hey @AlpenDitrix, could you split this into two separate PRs so that the bugfix can be reviewed separately from the refactoring?

In the bugfix PR could you clearly describe the bug you have been running into ?

Thanks!

**Pull request closed without merging**
