### PR TITLE
Add unitest for vcf standard header lines following #654

### PR DESCRIPTION
**Pull request by SHuang-Broad**
### Description

This PR includes some code clean up and updated unit tests for `VCFStandardHeaderLines`.

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by SHuang-Broad** [comment]
@droazen and @lbergelson , would either of you please review?
Thank you!

**Comment by nh13** [comment]
👍

**Comment by SHuang-Broad** [comment]
@nh13 . Thanks for taking a look, but I'm not able to merge this since I'm not a contributor yet. 
If you think this is ready, please let me know and I'll squash the commits.
Thank you!

**Comment by nh13** [comment]
Squash the commits and once the tests pass, this looks fine to me.

**Pull request merged**
