### PR TITLE
add SINGULAR platform to read group

### PR DESCRIPTION
**Pull request by omicsorama**
### Description

This change is to allow Singular Genomics platform id in read groups. This update adds support for new sequencing vendor platform

### Things to think about before submitting:
- [ X ] Make sure your changes compile and new tests pass locally.
- [ X ] Add new tests or update existing ones:
  - A bug fix should include a test that previously would have failed and passes now.
  - New features should come with new tests that exercise and validate the new functionality.
- [ X ] Extended the README / documentation, if necessary
- [ X ] Check your code style.
- [ X ] Write a clear commit title and message
  - The commit message should describe what changed and is targeted at htsjdk developers
  - Breaking changes should be mentioned in the commit message.

### CODE REVIEW

**Comment by lbergelson** [comment]
@omicsorama Hello.  I see you also have a [specs change](https://github.com/samtools/hts-specs/pull/686) proposed to add this value.  I'm happy to add this update this but I'm going to wait for a bit in case there's any feedback on that pr.  

Are you a representative of Singular?  Are they producing data with this value at the moment?

**Comment by omicsorama** [comment]
@lbergelson Yes i made the parallel PR to keep docs and tool in step. Makes sense to wait a bit for feedback. Thanks.

Yes [I](https://www.linkedin.com/in/palak-p-sheth/) am on the Bioinformatics team at Singular and we are holding off on producing data with this value until our customers can use a published htsjdk version that supports it

Happy to address any other questions!

**Comment by lbergelson** [comment]
@omicsorama Thanks for the info.  It seems like it should be uncontroversial then if the name is coming straight from the source.

**Comment by lbergelson** [comment]
This seems to have been merged in specs so I'm going to merge it.  Thank you @omicsorama

**Pull request merged**
