### PR TITLE
deleting SAMFileReader and SAMTruncatedFileReader

### LINKED ISSUE #695: Attack of the zombies! (SAMFileReader/SAMFileTruncatedReader)
The release notes for 2.5.0 say that SAMFileReader and SAMFileTruncatedReader have been deleted.

However, they still exist on master. It looks like there has been a merge muckup that resurrected these files.

### PR DESCRIPTION
**Pull request by lbergelson**
### Description

The long deprecated `SAMFileReader` and `SAMTruncatedFileReader` were supposed to be deleted in #602.  They seem to have been resurrected during the move to gradle.

Fixes #695 

renamed `SAMFileReaderTest` to the more accurate `SamReaderTest`
updated usages of `SAMFileReader` in the documentation to be `SamReader`

### Checklist

- [x] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by droazen** [comment]
Can you check to make sure these classes are not used in either Picard or GATK3?

**Comment by lbergelson** [comment]
@droazen Both Picard and GATK3 make use of them.  How to proceed?

**Comment by droazen** [comment]
@lbergelson Recommend that we open PRs (or at least, issues) against Picard and GATK3 to remove the usages before merging this.

**Comment by lbergelson** [comment]
@droazen Opened issues and rebased this.  Should we wait for them to be resolved or merge this before that happens?

**Comment by droazen** [comment]
@lbergelson I'd say wait until the Picard one is merged, since it's simple, but don't wait for GATK3.

**Comment by lbergelson** [comment]
Uses were removed from both GATK and Picard so I'm going to merge this.

**Pull request merged**
