### PR TITLE
Set compression level for GZIP files

### PR DESCRIPTION
**Pull request by nnordborg**
I have added IOUtil.setDefaultCompressionLevel() to make it possible to change the compression level for GZIP files that are opened for writing. The code is similar to what already exists in BlockCompressedOutputStream and is intended to be used in the same way (eg. in picard.cmdline.CommandLineProgram).

### CODE REVIEW

**Comment by vdauwera** [comment]
@nnordborg Same question as for your PR to picard -- are you still pursuing this actively or can we close this PR for now?

**Comment by nnordborg** [comment]
We deployed it in our server environment. It works but seems like it didn't made as much difference as some was hoping for.

**Comment by nh13** [comment]
Could you squash these commits and then we can include nonetheless?

**Comment by nnordborg** [comment]
I am not so familiar with git... not really sure what you mean with 'squash the commits'. I guess I need to do some 'rebase' command, but whatever I try I can't get any other response than  'Rebase did nothing. HEAD was already up-to-date'. 

Also, I am not sure why there are 6 commits listed above. Only the last one was committed in the 'compression-level' branch.

**Comment by nh13** [comment]
I rebased the commits for you (used ```git rebase -i```).  Tracking this here: https://github.com/samtools/htsjdk/pull/271

**Pull request closed without merging**
