### PR TITLE
adding a method to convert a FASTQ header (read name) to a read name

### PR DESCRIPTION
**Pull request by nh13**
string usable for output in a SAM or BAM file.

[Review on Reviewable](https://reviewable.io/reviews/samtools/htsjdk/431)

### CODE REVIEW

**Comment by nh13** [comment]
@yfarjoun, @tfenne, @droazen  could you take a look?  I found this method useful in a few different tools outside of htsjdk, so I decided to add it in.

**Comment by tfenne** [comment]
Looking at the tests I was surprised by this one:
`{"Name/1", true, false, "Name/1"}`

Wouldn't you want to always remove any trailing `/1` or `/2` from paired reads?  Otherwise the template names won't match in the resulting SAM file?  

I'd also be tempted to change it to take a single parameter `stripMateNumber` instead of the two booleans, and let the user decide how to set it.

**Comment by tfenne** [comment]
@nh13 I think this PR is waiting on you to reply to my comment/question, and then rebase.

**Comment by akiezun** [comment]
@tfenne should we reassign to @nh13 then (if it's waiting on @nh13 )?

**Comment by nh13** [comment]
@tfenne rebased and simplified based on your suggestions.  Thanks for the review.

**Pull request merged**
