### PR TITLE
Test for Silent bug when query a compressed indexed reference file

### PR DESCRIPTION
**Pull request by ffinfo**
### Description

This code is only to show the issue. Initial the tests will fail on this PR.

When executing <IndexedFastaSequenceFile>.getSubsequenceAt the method gives wrong results but not a exception that this is not yet supported, see also https://github.com/samtools/htsjdk/issues/864

I have added here a test that is currently failing.

Here there are 2 possible solutions:
- Implement https://github.com/samtools/htsjdk/issues/864 (preferred)
- Raise a exception when the method is called (workaround)

### Checklist

- [ ] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by lbergelson** [comment]
This is really nasty.  We should probably make this throw until we can properly support fasta.gz.

**Comment by cmnbroad** [comment]
This should be addressed by https://github.com/samtools/htsjdk/pull/1014.

**Comment by magicDGS** [comment]
Now this is not longer an issue - in the master branch there is support for bgzip FASTA files!

**Comment by lbergelson** [comment]
@ffinfo I'm going to close this because the issue is fixed and your test has been incorporated into the branch that fixed.  Thank you for bringing this to our attention.  It's always helpful to have a failing test to show off a problem.

**Pull request closed without merging**
