### PR TITLE
switching from coverals to codecov

### PR DESCRIPTION
**Pull request by lbergelson**
codecov seems to be more accurate since it incorporates a notion of "partially covered lines"
it also makes reviewing pr's easier since coverage can be shown inline during reviews with a browser plugin

### CODE REVIEW

**Comment by lbergelson** [comment]
don't merge this, it isn't capturing the sra test coverage yet

**Comment by yfarjoun** [comment]
I love the report that Codecov creates...makes me want to start writing
tests....:-)

**Comment by lbergelson** [comment]
@yfarjoun Have you seen the browser plugin that lets you see which lines of a pull request are covered and which aren't?

**Comment by lbergelson** [comment]
@yfarjoun I'm not certain but I suspect that if the SRA tests started working the coverage would be included now.  Could you review this?

**Pull request merged**
