### PR TITLE
Provide a method in VariantContextWriterBuilder to set an option depe…

### PR DESCRIPTION
**Pull request by nh13**
### Description

This will allow chaining of the set/unset methods with conditionals.  See https://github.com/broadinstitute/picard/pull/525 for where I use this method.

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

…nding on a Boolean.

### CODE REVIEW

**Comment by droazen** [comment]
Looks fine, but can you add a quick unit test for the new method? Feel free to merge once the test is added.

**Comment by nh13** [comment]
My strong preference (and others may feel this way too) would be not to have unit tests for such a small and easily verifiable change.  The other set/unset methods aren't tested and really should they be given their trivial implementation? Anyhow, to not block this PR with a debate about testing I have added the unit tests.

@droazen could you look again?

**Comment by droazen** [comment]
@nh13 `VariantContextWriterBuilder.clearOptions()` is also a "trivial" method, and yet we once had a horrible bug involving it due to lack of continuous tests (see https://github.com/samtools/htsjdk/commit/565c0643a48760730735d760caf1c4c926765f5d). My preference would be to err on the side of too much testing in htsjdk -- for public methods, at least.

Anyway, this looks good, merge at will :+1:

**Comment by nh13** [comment]
@lbergelson or @droazen is there a chance of an htsjdk release so that this can be used in a Picard PR (https://github.com/broadinstitute/picard/pull/525)?  I think Picard now clones the latest htsjdk release (https://github.com/broadinstitute/picard/commit/4fee6769a93c065d91a65d306fa56f22182cd0ec).

**Comment by droazen** [comment]
@nh13 Sure, we can do a release (provided the new "integration/downstream" tests all pass.

**Comment by lbergelson** [comment]
@nh13 I'll do a 2.2.4 release when the integration tests finish.

**Comment by lbergelson** [comment]
@nh13 2.2.4 is released

**Pull request merged**
