### PR TITLE
public reg2bin

### PR DESCRIPTION
**Pull request by lindenb**
### Description

Moved GenomicIndexUtil.reg2bin to public

I'm inserting genomic data in a sql database just like in the UCSC tables : there is a 'bin' index ( http://genomewiki.ucsc.edu/index.php/Bin_indexing_system )

making  `GenomicIndexUtil.reg2bin` public allows me to get the 'bin' index . 

### Checklist

- [ x] Code compiles correctly
- [ x] New tests covering changes and new functionality
- [ x] All tests passing
- [ x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by nh13** [comment]
The doc seems outdated, can you update them to not be specific to SAM, and link to the wiki perhaps? 
 Also, the method name could be a lot better, how about `regionToBin`?

**Comment by lindenb** [comment]
@nh13 back to you: I've renamed reg2bin to regionToBin and added a reference to the paper.
Thanks

**Comment by nh13** [comment]
@lindenb Could you add in the tests I made here, squash the changes, then I can merge?  https://github.com/samtools/htsjdk/commit/ee61abae034fa5cc6e3bbb0a91b39aa6ba7c1dc2

**Comment by lindenb** [comment]
@nh13 done ! :-)

**Comment by nh13** [comment]
@droazen @yfarjoun @akiezun want to give a 👍  and then we can merge?

**Comment by yfarjoun** [comment]
trusting you on this @nh13.

**Pull request merged**
