### PR TITLE
Test on Java 11

### PR DESCRIPTION
**Pull request by tomwhite**
### Description

Runs htsjdk's unit tests on Java 11.

### Checklist

- [ ] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by yfarjoun** [comment]
did you only open this to get the tests? is this a serious candidate for merging? in the current state, of course that would not be possible...

**Comment by tomwhite** [comment]
@yfarjoun the goal here is to check we can build and run htsjdk tests with Java 11. The source and target Java versions are *not* changed - they are still Java 8 - so this is just to ensure that we can use a Java 11 compiler and runtime with the current htsjdk source. It does not replace the Java 8-based build.

There were a few things I had to change to get this to work:
* Upgrade to Gradle 5 for Java 11 support
* Change a Scala method call in the tests to avoid a conflict with Java (see  https://github.com/scala/bug/issues/11125).
* Remove two javadoc comments that were causing the Java 11 javadoc tool to fail.

This is a serious candidate for merging, since none of these changes interfere with the current Java 8 build. I also added a `openjdk11` target to Travis so that every change is checked on Java 11. This will mean that htsjdk doesn't regress in its ability to be built with and run on Java 11.

**Comment by lbergelson** [comment]
Wow, those two javadoc comments were the issue?  I assumed it would be much worse than that.  Bizarre.  That shouldn't cause a javadoc null point exception...

**Comment by lbergelson** [comment]
@tomwhite This still had some issues with it, I pushed lb_java11 which should resolve them.  Would you like to incorporate those changes into yours or should I create a new pr?

**Comment by tomwhite** [comment]
@lbergelson thanks for looking at this. I had a look at your branch, but it wasn't clear how the changes related to Java 11. That said, please go ahead and merge as you see fit.

**Comment by lbergelson** [comment]
@tomwhite They fix problems introduce by moving to gradle 5.  It broke the `maven` publication so I switched it to the newer `maven-publish` which seemed to fix the problem.   I bumped a few versions of things and did a little cleanup to remove newly deprecated stuff as well.

**Comment by lbergelson** [comment]
closing this since I've taken it over in #1291

**Pull request closed without merging**
