### PR TITLE
Proposal: deprecate or remove SAMTools.java

### PR DESCRIPTION
**Pull request by magicDGS**
### Description

The `SAMTools` class does not add anything to the HTSJDK library except an example of how to iterate over a SAM/BAM file. In addition, it is not tested. I propose to either deprecate (first commit) or delete (second commit) this class.

I think that if HTSJDK is a library, we should clean up untested classes that does not add anything to the codebase, and are not really useful for an API user. 

### Checklist

- [x] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by lbergelson** [comment]
@magicDGS I agree with removing this.  I think we should deprecate it first though for at least a release or two on the off chance that someone is relying on it for something.

**Comment by magicDGS** [comment]
Sure @lbergelson. I reverted the last commit.

**Comment by lbergelson** [comment]
@magicDGS 👍

**Comment by magicDGS** [comment]
Thanks @lbergelson!

**Pull request merged**
