### PR TITLE
Simplify BufferedLineReader by using LineNumberReader

### PR DESCRIPTION
**Pull request by magicDGS**
### Description

`BufferedLineReader` had a `TODO` to be replaced by the `LineNumberReader` instead. This commit simplify the `BufferedLineReader` by extending `LineNumberReader`.

If the original purpose is to remove completely the `BufferedLineReader` class, this commit can also deprecate it and replace the usages for the `LineNumberReader`. Nevertheless, I do not know if this is possible because I haven't check it.

### Checklist

- [x] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by pshapiro4broad** [comment]
Can you also re-implement `StringLineReader` using `BufferedLineReader` with a `ByteArrayInputStream`?

**Comment by magicDGS** [comment]
Hi @pshapiro4broad, I will do in a different PR to keep the two changes independent.

**Comment by pshapiro4broad** [comment]
@magicDGS I may be wrong, but I believe `StringLineReader` can be replaced with something like:
```
public class StringLineReader extends BufferedLineReader {
    public StringLineReader(final String s) {
        super(new ByteArrayInputStream(s.getBytes()));
    }
}
```
It's not really part of what you're doing, but it seemed like it would be an easy fix if it worked.

**Comment by magicDGS** [comment]
@pshapiro4broad: If that simplification works (that I'm sure it will), I think that I will open a different PR to make the simplification. In addition, I think that in that case the class is unnecessary and could be deprecated in favor of an static method in `BufferedLineReader` to construct from a `String`.

Anyway, could you merge this branch if it's ok or nominate someone with credentials to do it, @pshapiro4broad?

**Comment by pshapiro4broad** [comment]
I agree with your suggestion to deprecate and add a static method, and use a separate PR.

I don't have write access to this repo. I think @lbergelson can help.

**Comment by lbergelson** [comment]
@magicDGS 👍 Merging this.

**Comment by magicDGS** [comment]
Thanks @lbergelson!

**Pull request merged**
