### PR TITLE
Make VCFHeader Serializable

### PR DESCRIPTION
**Pull request by droazen**
This was missed in the previous pull request to make SAM/Variant
records Serializable. We want to be able to serialize VCFHeaders
just as we do SAMFileHeaders

### CODE REVIEW

**Comment by droazen** [comment]
For @lbergelson to review please

**Comment by lbergelson** [comment]
@droazen Looks good to me.
@mattsooknah Can you run whatever needs to be done to test this for picard?

**Comment by droazen** [comment]
Strange, the serialization test passes for me locally but fails on travis. Will investigate

**Comment by lbergelson** [comment]
What's the failure say?

**Comment by droazen** [comment]
It says the header metadata mismatches, but the expected/actual output is identical, and the same assert passes locally for me in both Java 7 and 8.

**Comment by lbergelson** [comment]
Is it failing only on a specific jvm, or in all of them on travis?

**Comment by droazen** [comment]
All of them -- am experimenting now to try to narrow down the problem.

**Comment by droazen** [comment]
Believe I've fixed it -- the various classes extending `VCFHeaderLine` overrode `equals()` but not `hashCode()`, violating contract, and their `equals()` methods did not properly chain up the class hierarchy. @lbergelson re-review at your leisure.

**Comment by mattsooknah** [comment]
:+1: in terms of picard public/private compatibility.

**Comment by lbergelson** [comment]
@mattsooknah Thanks again!

**Comment by lbergelson** [comment]
@droazen :+1:

**Pull request merged**
