### PR TITLE
Yf intel unittest

### PR DESCRIPTION
**Pull request by yfarjoun**
### Description
An attempt to add a unit test for testing the intelDeflator in travis based on the PR by @mishalinaik #524 
### Checklist

- [ x ] Code compiles correctly 
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

NOTE: tests are currently failing...with a 

`
SIGSEGV (0xb) at pc=0x00000037c5c7a258, pid=43462, tid=47020643018496
`

not sure what is wrong...can I solicit some help on this @mishalinaik ?

### CODE REVIEW

**Comment by mishalinaik** [comment]
@yfarjoun What would you like me to look into?

**Comment by yfarjoun** [comment]
Sorry, I requested help too quickly...seems to be working again now...I'll
ping you again when I"m done fiddeling with this. sorry for the back and
forth.

**Comment by mishalinaik** [comment]
@yfarjoun It seems the crash happens on Ubuntu based on the Travis build information, will look into it.

**Comment by akiezun** [comment]
@yfarjoun is this PR redundant now given your #536?

**Comment by yfarjoun** [comment]
yes.

**Pull request closed without merging**
