### PR TITLE
Fixed naming inconsistency in SamLocusIterator

### PR DESCRIPTION
**Pull request by superbobry**
### Description

The method named `getRecordAndPositions` returned a list of `RecordAndOffset` objects which was a bit confusing. 
### Checklist
- [x] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by yfarjoun** [comment]
There's a large PR that is changing similar code (#637). Could you rebase after they merge?

**Comment by superbobry** [comment]
I think you can now merge-rebase via GitHub UI?

**Comment by yfarjoun** [comment]
not if there are conflicts, and there will be....that's why I want the other PR to go in first.

**Comment by superbobry** [comment]
Okay, just lmk when the other PR gets merged.

**Comment by yfarjoun** [comment]
@lbergelson please be advised that I asked that this PR wait for another larger one that will be in  conflict with this one...

**Comment by yfarjoun** [comment]
This can now be rebased over the latest master.

**Comment by superbobry** [comment]
Hmm, I'm surprised GH also pulled in the Gradle commit.

**Comment by yfarjoun** [comment]
@lbergelson can you take a look here? I'm not sure why there are gradle-related changes here....

**Comment by lbergelson** [comment]
So, I think that what happened here is that @superbobry rebased onto master, but accidentally squashed his commit into the last commit that was already on master.  I think we're seeing a display issue on github where it's showing the actual commit diffs, not the diff between master and this commit.  Merging should be safe, but the authorship will be screwed up.  I think it's going to list me as the author and not suprbobry.  

@superbobry If you want to fix it, I think you can go in and manually --amend your commit to unstage the changes to the gradle files and fix the author to be you.  Then rebase on top of master again.  If you don't care, let me know and I can merge them in as is.

**Comment by superbobry** [comment]
@lbergelson frankly, I don't care enough to go through amend and rebase, so feel free to merge this as is. Thanks!

**Comment by lbergelson** [comment]
@superbobry Merged.  Github managed to figure out the authorship issue automatically somehow, so it is represented correctly as your contribution.  Thanks for the patch and sorry for the unnecessary pain.

**Pull request merged**
