### PR TITLE
squid:SwitchLastCaseIsDefaultCheck - switch statements should end wit…

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar squid:SwitchLastCaseIsDefaultCheck - "switch" statements should end with a "default" clause

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:SwitchLastCaseIsDefaultCheck

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by lbergelson** [comment]
Restarted tests.  This seems pointless to me.  Just adding ` default: break;` to these may be worse than leaving them default less.  It will hide warnings that might be generated if there were missing cases for a number of these.  Some of these would probably be improved by throwing exceptions if an unexpected case is encountered.  It's too bad java doesn't have compilation failures for switches with missing enum values and no default...

**Comment by akiezun** [comment]
I think this is fine. Having an explicit default is cleaner. Let's merge this unless someone objects, wdyt?

**Comment by yfarjoun** [comment]
I second @lbergelson's objection. if not all cases are dealt with, an IDE
could generate a warning (if someone adds an ENUM value in the future),
with a "default" case it will not.

:-1: from me.

**Comment by akiezun** [comment]
ok, in that case, unless we find a champion for this PR, let's close.

**Comment by lbergelson** [comment]
Closing this. Thanks @m-ezzat, but we're going to pass on this.

**Pull request closed without merging**
