### PR TITLE
Change default logging level to INFO

### PR DESCRIPTION
**Pull request by ronlevine**
### Description

Implements https://github.com/samtools/htsjdk/issues/739.
Do not want to get DEBUG messages by default.

### Checklist

- [X] Code compiles correctly
- [X] New tests covering changes and new functionality
- [X] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by ronlevine** [comment]
@vdauwera Please review.

**Comment by vdauwera** [comment]
Looks good to me.

Anybody out there have strong opinions about this change, before we merge?

**Comment by ronlevine** [comment]
@vdauwera Going once, going twice, merge?

**Comment by vdauwera** [comment]
Maybe give people until tomorrow, unless there's an imminent release?

**Comment by ronlevine** [comment]
@vdauwera How about you merge when you feel the time is right...

**Comment by vdauwera** [comment]
Yeah no one has piped up...

**Pull request merged**
