### PR TITLE
Kt varient context change

### PR DESCRIPTION
**Pull request by yfarjoun**
### Description

making the changes requested in #657

Fixes for broadinstitute/picard#519
### Checklist
- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [x] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by yfarjoun** [comment]
@lbergelson this was reviewed by you in a different incarnation...can you check that it does what you want now?

**Comment by lbergelson** [comment]
@yfarjoun It looks right to me, but could you add a unit test?  That function is totally untested.

**Comment by yfarjoun** [comment]
done.

**Comment by lbergelson** [comment]
@yfarjoun One of the tests is failing.

**Comment by yfarjoun** [comment]
hmmm. need to figure out why tests are failing!

**Comment by yfarjoun** [comment]
@lbergelson fixed test, OK to merge?

**Comment by lbergelson** [comment]
@yfarjoun 👍

**Pull request merged**
