### PR TITLE
Maintain ordering of header

### PR DESCRIPTION
**Pull request by ronlevine**
### Description

Implements https://github.com/samtools/htsjdk/issues/847.

### Checklist

- [X] Code compiles correctly
- [X] New tests covering changes and new functionality
- [X] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by ronlevine** [comment]
@lbergelson Please review.

**Comment by ronlevine** [comment]
@yfarjoun Could you take a look? Louis will be on vacation.

**Comment by yfarjoun** [comment]
looks good @ronlevine. Could you split into two commits, test and code change and push them separately (so that travis will initiate a build on both commits)? I'd like to see that the old code breaks the tests.

**Comment by ronlevine** [comment]
@yfarjoun Done. Take a look at the last 2 travis runs.

**Comment by yfarjoun** [comment]
Thank @ronlevine. :+1:

**Pull request merged**
