### PR TITLE
Add unit tests for validation methods in VariantContext

### PR DESCRIPTION
**Pull request by abaumann**
There will be unit tests that test the functionality of:
extraStrictValidation
validateReferenceBases
validateRSIDs(rsIDs);
validateAlternateAlleles();
validateChromosomeCounts();

The extraStrictValidation method calls all the other methods,
so the test for this makes use of the data providers for the
other tests - I couldn't think of a better way to do this,
and someone could change what extraStrictValidation does, so
it seemed safest to provide a test for it.  Each method has
a pass and a fail test for all the conditions I could think of.

Resolves: #203

### CODE REVIEW

**Comment by vdauwera** [comment]
@abaumann Is this still in progress or is it ready to be reviewed?

**Comment by abaumann** [comment]
There's a pull request that just needs to be reviewed

**Comment by nh13** [comment]
:+1: squash and merge

**Comment by akiezun** [comment]
@abaumann rebase squash and merge

**Comment by abaumann** [comment]
I believe this should be good to go now

**Pull request merged**
