### PR TITLE
Proposed addition of a backward compatibility checkbox to the PR template.

### PR DESCRIPTION
**Pull request by cmnbroad**
### Description

Propose adding a checkbox for backward compatibility to the PR template.

### CODE REVIEW

**Comment by lbergelson** [comment]
@cmnbroad Maybe we should add an automated check as well using something like [japicmp](https://github.com/siom79/japicmp).

**Comment by akiezun** [comment]
agreed, manually determining if two versions are binary compatible is definitely non trivial: https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html

**Comment by cmnbroad** [comment]
True that, but I think 99% of the time the coder knows they're making an incompatible change when they do it. I just wanted something to alert the reviewers so we can set the version tag on the PR and make the breaking ones easy to find when we have to go hunt them down.

**Comment by droazen** [comment]
I think this is fine as long as it's understood that this is a flag set by a human to alert project maintainers of possible breakage, rather than a comprehensive means of determining which commits have broken compatibility. @cmnbroad merge when ready

**Pull request merged**
