### PR TITLE
Read no_ref crams

### PR DESCRIPTION
**Pull request by sd4B75bJ**
### Description

Adding support for reading no_ref CRAMs

samtools#721

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by cmnbroad** [comment]
@sd4B75bJ Thanks for submitting a PR to htsjdk. Unfortunately, the problems with RR go deeper than just the MD5 check, so relaxing the MD5 validation fixes only the symptom, not the underlying problem. The CRAM code as it stands doesn't correctly handle read features for RR=0. If you look at what happens in your test case, the bases for the reads are being pulled directly from the reference (which the caller is still required to provide) rather than from the `Bases` read features that are embedded in the CRAM file.

A refactoring of much of the CRAM code is currently in progress on another branch in order to address those and other issues. Once thats done and tests are put in place to verify that the read bases are correctly round tripped, then the  MD5 check, along with the requirement to always provide a reference, can relaxed.

**Comment by cmnbroad** [comment]
@sd4B75bJ Closing based on previous comments - feel free to reopen/comment if I've missed something.

**Comment by sd4B75bJ** [comment]
@cmnbroad okay sounds reasonable, thanks for reviewing. Sorry, could you point me at the main CRAM refactoring branch that you refer to above?

**Comment by cmnbroad** [comment]
@sd4B75bJ The refactoring is being done in waves, so there are actually a series of PRs and branches underway, in various states of readiness. i.e., https://github.com/samtools/htsjdk/pull/1374, https://github.com/cmnbroad/htsjdk/tree/cn_cram_compression_header_factory, https://github.com/samtools/htsjdk/pull/1164, https://github.com/samtools/htsjdk/pull/1348, https://github.com/samtools/htsjdk/pull/1349, to name a few.

**Pull request closed without merging**
