### PR TITLE
Switched to relative lib path for deflator so Picard public release s…

### PR DESCRIPTION
**Pull request by jacarey**

### CODE REVIEW

**Comment by lbergelson** [comment]
@jacarey Was this necessary because of the sbt changes I made?  I didn't think that would affect picard at all since it shouldn't change the layout of the checkout out htsjdk repo..

**Comment by jacarey** [comment]
@lbergelson The issue is that the picard release script calls htsjdk tests for its own directory which gets set as user.dir and so the intel tests attempt to find the deflator in picard/lib/jni instead of picard/htsjdk/lib/jni

**Comment by lbergelson** [comment]
@jacarey Ah, so sounds unrelated to what I was doing.  I didn't break everything! Woo.

**Comment by jacarey** [comment]
@lbergelson Nope in fact it only broke the release script and the change was simple enough to fix.

**Pull request merged**
