### PR TITLE
The existing code was throwing a NPE when using a CRAMFileReader for …

### PR DESCRIPTION
**Pull request by skashin**
…InputResource.Type.PATH

### Description

Please explain the changes you made here.
Explain the **motivation** for making this change. What existing problem does the pull request solve?

### Checklist

- [ ] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by yfarjoun** [comment]
Thanks for this.

this needs to be protected against future changes...can you please convert the list of `if` statements to a `switch` that includes a `default` case that will throw an exception? that should make things more clear when they break....

**Comment by skashin** [comment]
No problem, I switched away from the if statements

**Comment by yfarjoun** [comment]
much better, thanks.

**Comment by yfarjoun** [comment]
I guess you could revert the revert in a new branch and run the tests....or submit a PR and have travis test for you.

**Comment by skashin** [comment]
I ran "./gradlew test", and that built successfully.
What exactly did you mean by "somehow it broke the build"?

**Comment by yfarjoun** [comment]
@lbergelson can you help here?

**Pull request merged**
