### PR TITLE
Class for writing fasta format file.

### PR DESCRIPTION
**Pull request by alecw**
### Description

Class for writing fasta format file moved from private repo to public.  Enables use of this code in other public repositories.

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by lindenb** [comment]
wouldn't it be better to use an interface + a factory pattern ? something like:

`new FastaWriterFactory().setLineLength(50).open(thefile).add("name","atgagatc").close();`

**Comment by alecw** [comment]
My opinion is that making this change would add a bunch of additional code that ultimately won't provide much value because I don't see this class accumulating a ton of option like, e.g. SAMReader.  That said, if the consensus is that I should do it as Pierre suggests, I will do so.

> @lindenb: 
> wouldn't it be better to use an interface + a factory pattern ? something like:
> new FastaWriterFactory().setLineLength(50).open(thefile).add("name","atgagatc").close();

**Comment by yfarjoun** [comment]
There are a few options that I see the value in being able to add/modify:

- output format (fasta / gzipped fasta) but that should go by filename
- create dictionary on the fly
- create index on the fly

I'm not saying we need to add these now, but it would be good to think about how one would add them in the future without breaking the API. 

A factory does allow for that. 
As do non-factory setters. 

@lbergelson @tfenne @jacarey ?

**Comment by magicDGS** [comment]
A nice implementation of what @yfarjoun mentioned: https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/reference/FastaReferenceWriter.java

Maybe worth to port a that from GATK4?

**Comment by lbergelson** [comment]
I think we should port and update the GATK version instead since it already handles a lot of the things that we want, like creating the index and dictionary. While we're at it we should make it support bgz fasta and create the GZI index for it.

**Comment by yfarjoun** [comment]
@alecw, sorry for the time-lag. We would like to eventually use the GATK-ported version which will be a api change. we could merge this version as a "BETA" version and then change the API, or wait till someone ports the GATK version. Do you have a preference?

**Comment by yfarjoun** [comment]
replaced by #1172

**Pull request closed without merging**
