### PR TITLE
Un-deprecating GenotypeBuilder.log10PError

### PR DESCRIPTION
**Pull request by lbergelson**
it is still in use and has no replacement

### CODE REVIEW

**Comment by lbergelson** [comment]
@mattsooknah you seem to be the person to look at these

**Comment by mattsooknah** [comment]
Looks good. Although there's something Zen about the statement "Will be retired when"

**Comment by nh13** [comment]
Where is this being used?

**Comment by mattsooknah** [comment]
It's used in GATK (GATKVariantContextUtils).

**Comment by lbergelson** [comment]
GATK/hellbender

**Comment by nh13** [comment]
Move it there and delete it from HTSJDK. 

N

Thumb typed for added typos

**Comment by akiezun** [comment]
that sounds like a suboptimal solution here. Let's just remove the
@Deprecated

**Comment by nh13** [comment]
If it is only used in the GATK and it has been deprecated we should move it out. 

N

Thumb typed for added typos

**Comment by nh13** [comment]
Flip-flop, if the plan is to add more utility tools into htsjdk then lets remove the deprecation.

**Comment by mattsooknah** [comment]
It appears to have been deprecated when it was brought over to HTSJDK, two years ago. It converts from log10(p(calling error)) to the corresponding Phred score, by just multiplying by -10. 

Thus I would infer that it was supposed to be retired when GATK could report the likelihood directly as a Phred score. Was this ever planned to happen?

If Phred-scaling is supposed to be the realm of HTSJDK, then it should stay there; otherwise we should move it to GATKVariantContextUtils, I think.

**Pull request merged**
