### PR TITLE
Remove deprecated SAMRecordUtil

### PR DESCRIPTION
**Pull request by magicDGS**
### Description

`SAMRecordUtil` class was deprecated 6 releases ago, and I think that it is fair to remove this class for next release. At least two actively developed projecs (Picard and GATK4) already removed the deprecated usages.

### Checklist

- [x] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by magicDGS** [comment]
Because this is maintainer work, could you have a look @lbergelson, @tfenne, @jacarey?

**Comment by magicDGS** [comment]
Now this code is even more "ancient": any thoughts about removal, @lbergelson, @tfenne, @jacarey?

**Comment by tfenne** [comment]
I'm fine with this.  @lbergelson or @jacarey any objections?

**Comment by lbergelson** [comment]
👍

**Pull request merged**
