### PR TITLE
Changed aux files names for windows compatibility.

### PR DESCRIPTION
**Pull request by jacarey**
Fix for https://github.com/samtools/htsjdk/issues/157

### CODE REVIEW

**Comment by gbggrant** [comment]
:+1: looks good (providing tests pass).
I did not know that you cannot name a file 'aux.*' in Windows.  Evidently other port names are forbidden too i.e. (COM1, COM2, LPT1...)
Stupid Ol' Windows

**Comment by nh13** [comment]
@jacarey test failed :/

**Comment by jacarey** [comment]
Actually it is still running. 58 minutes later :(

**Comment by jacarey** [comment]
Tested fine locally

**Pull request merged**
