### PR TITLE
proppagate ValidationStringency from CRAMFileReader to CRAMIterator

### PR DESCRIPTION
**Pull request by vadimzalunin**
https://github.com/samtools/htsjdk/issues/394

### CODE REVIEW

**Comment by vadimzalunin** [comment]
@droazen @akiezun please review

**Comment by lbergelson** [comment]
@vadimzalunin Looks good.  Could you add a test that proves that it's fixed for the case that is described in #394?  I.e. an example query call that fails with strict validation but passes with silent validation.

**Comment by cmnbroad** [comment]
We already have a setter/getter for validation stringency on the iterator, so I'm wondering if we can't just use those to fix this bug. It looks like this change breaks backward compatibility for CRAMIterators - I'm just not sure how those kinds of changes are handled with htsjdk. Can we make changes like that to public APIs ?

**Comment by lbergelson** [comment]
@cmnbroad It's a good point.  My thinking was the following:

1. The coming release is going to break backwards compatibility in a number of small ways already.
2.  The cram support is still very new and I was thinking it's essentially still and alpha interface. 
3.  Respecting validation stringency is pretty important, and it's easy to forget to set it if it's not done in the constructor.  

If people think it's dangerous to change these constructors I'm fine with that too though.

**Comment by lbergelson** [comment]
We need to define a policy for experimental API's so that we can feel free to revise things while they're still under heavy development.  I started a thread about it here, but we didn't reach any conclusion...  #378

**Comment by cmnbroad** [comment]
Yeah we definitely need something like that. It sounds like we should move ahead with this for now though.

**Comment by vadimzalunin** [comment]
@cmnbroad  I was thinking about using the setter but then realized that all calls to CRAMIterator constructors are followed by setValidation method. 
As for changes to public API, I agree that CRAM should be allowed to change for now.

**Comment by lbergelson** [comment]
we merged this in so that it's fixed for the release we're doing now.  We should still add that test.

**Comment by tomwhite** [comment]
I agree with @cmnbroad's point about not breaking backward compatibility. This has caused a problem already, see https://github.com/broadinstitute/gatk/issues/1247.

**Pull request merged**
