### PR TITLE
Issue #196 - fixes a bug which causes an overflow in the CIGAR when a…

### PR DESCRIPTION
**Pull request by nenewell**
… BAM file is parsed that contains a read that spans a very large intron. The bug is caused by the use of an arithmetic (>>) rather than a logical (>>>) right shift operator in BinaryCigarCodec.binaryCigarToCigarElement(). This fix substitutes the logical for the arithmetic operator, and implements a test which reads the sample BAM file (containing a single record) that exposed the bug and compares the indexing bin field with the computed indexing bin field. If the two fields are different, an error is thrown.

### CODE REVIEW

**Comment by vdauwera** [comment]
Looks good, just checking with the user who reported the issue that we can use his bam for the test.

**Comment by nenewell** [comment]
Rebased.

**Comment by vdauwera** [comment]
#196

**Comment by vdauwera** [comment]
Ack, user hasn't responded to my request for permission to include the test file in the codebase. Emailed him directly. I'm probably being overly careful but it's better than the opposite...

**Comment by nenewell** [comment]
Agreed.

**Comment by vdauwera** [comment]
Got confirmation that it's cool. Merging.

**Comment by nenewell** [comment]
Thank you – I’m on the board!

**Pull request merged**
