### PR TITLE
Publish snapshots from master.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by kshakir** [comment]
Pinging @lbergelson, @jacarey, @geoffjentry, or @vdauwera for (at least one?) review.

Again, was trying not to change the build.sbt defaults for whomever was publishing releases manually. If a reviewer would like, happy to move some of these options from travis.yml into defaults in build.sbt.

Completes #175.

**Comment by vdauwera** [comment]
I can only say :dog: as stand-in for hipchat `(noidea)`

But in principle I am for it.

**Comment by geoffjentry** [comment]
Fine by me but would be more comfortable if someone else took a look as well

**Comment by lbergelson** [comment]
Looks good to me.  Will picard be able to depend on an htsjdk compiled with java 8?

**Comment by kshakir** [comment]
@lbergelson I didn't consider Picard. Updated this PR to push a Java 7 build instead. (Also fixed the [-2 issue](http://forums.jfrog.org/Snapshot-versioning-td7480017.html) and updated the [docs](https://broadinstitute.atlassian.net/wiki/display/DSDE/Artifactory).) I still have no idea what's being manually published for the central release of htsjdk, but the snapshot automation in `.travis.yml` can easily be tweaked to match.

For continued support of [legacy](https://www.java.com/en/download/faq/java_7.xml) builds, we could also publish using [classifiers](http://maven.apache.org/pom.html#Dependencies), like [HikariCP](https://github.com/brettwooldridge/HikariCP#-hikaricpits-fasterhikari-hikalē-origin-japanese-light-ray) sort of does, or more correctly like TestNG [used to publish](http://search.maven.org/#artifactdetails%7Corg.testng%7Ctestng%7C5.5%7Cjar).

I'd prefer if that were another github issue though. For closing #175, I'd like to see what's in this PR: some non-classified `-SNAPSHOT` published, that previews the current non-classified release to central.

**Comment by lbergelson** [comment]
@kshakir I wouldn't worry to much about supporting legacy versions.  The plan is to upgrade htsjdk to java 8 in october, so it's not a long period of time until then.

**Comment by vdauwera** [comment]
@akiezun This is the htsjdk issue we discussed

**Pull request merged**
