### PR TITLE
Removed gelitext package (deprecated)

### PR DESCRIPTION
**Pull request by magicDGS**
### Description
Cleaning up some long-deprecated classes from gelitext, tests and usages. Found in #707.

### Checklist

- [x] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

**Comment by lbergelson** [comment]
Is there anyone in the world who still uses Geli?  If so... please comment on this pull request...

**Comment by magicDGS** [comment]
Updated branch to remove conflicts.

**Comment by droazen** [comment]
@vdauwera Do you have an opinion on this one? GATK3 still has support for this format, but I'm not sure there are any users left.

**Comment by vdauwera** [comment]
No one has ever asked about it that I can remember, so I'd be comfortable killing it.

**Comment by droazen** [comment]
@vdauwera Full disclosure: there is an actual tool in GATK3 that would have to be deleted if this goes in (`VcfToGeliText`)

**Comment by vdauwera** [comment]
Is that a private tool? I've never even come across it that I can recall...

**Comment by droazen** [comment]
Yes, it's a private tool

**Comment by vdauwera** [comment]
Then kill away...

**Comment by magicDGS** [comment]
Everybody agrees on this?

**Comment by vdauwera** [comment]
👍

**Pull request merged**
