### PR TITLE
CRAM format support

### PR DESCRIPTION
**Pull request by SilinPavel**
**1. Picard Tools cannot use CRAM file as input for metrics**

Current version of Picard Tools cannot use CRAM file as input for metrics that don’t pass reference sequence directly to SamReaderFactory, despite the fact that each CommandLineProgram has an input parameter REFERENCE_SEQUENCE. 
For example, MarkDuplicates experiences such a problem: (https://github.com/broadinstitute/picard/issues/433, https://github.com/broadinstitute/picard/issues/361) 

To resolve this problem we suggest several changes in htsjdk: as @tfenne suggested (https://github.com/broadinstitute/picard/issues/433#issuecomment-183141150)  we propose to add a static field  referenceSequenceFromCmd with a static setter in SamReaderFactory. It allows Picard CommandLineProgram  to set field referenceSequenceFromCmd when REFERENCE_SEQUENCE is non-null and/or Defaults.REFERENCE_FASTA is set.

**2. CRAMFileReader throws exceptions when there is no reference.**

In current implementation CRAMFileReader throws exceptions "A valid CRAM reference was not supplied" or "A reference is required for CRAM readers" exceptions when there is no reference. However, there can be cases when reference is not really needed (CRAM with all reads unmapped).

Our proposition is not to throw any exception when no reference was defined in getDefaultCRAMReferenceSource, but just return empty ReferenceSource object. With this approach CramFileReader will only throw exception in runtime and only if there is no reference when it is really needed (CramFileReader’s constructors do not throw any exception when null reference is passed). Tests were fixed to fit these cases.

All these changes are needed for corresponding changes in PicardTools, that will provide option to handle CRAM file as input/output correctly (https://github.com/samtools/htsjdk/issues/366). We are going to publish the corresponding pull request to Picard Tools shortly.  
- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [x] All tests passing

### CODE REVIEW

**Comment by jabbarish** [comment]
@yfarjoun @tfenne Take a look at this PR from our team, please.

**Comment by cmnbroad** [comment]
I'm unclear on the need for the SamReaderFactory changes outlined for #1 above. Picard has to be changed one way or another to make CRAM work; those changes should be trivial using the existing htsjdk APIs. That seems preferable to me to adding a new API and new state to SamReaderFactory. As for #2, we probably need something like that based on all the recent discussion around not requiring a reference.

**Comment by bmkodoo** [comment]
@cmnbroad
Yes we agree that it's unclear. There are alternative ways:

1. To pass reference using existing htsjdk API is `SamReaderFactory#referenceSequence` factory chain method: to add this call to every metric and oblige to use it in future each time `SAMReader` opens.
2. Our current modification call `getDefaultCRAMReferenceSource` fallback chain if no reference is passed. So, reference can be passed to SamReaderFactory by `samjdk.reference_fasta` property.

@yfarjoun @tfenne, what do you think about those alternatives?

**Comment by ekazachkova** [comment]
As we can see, Picard has 11 classes which instance SamReader without reference set. They are:

- AbstractMarkDuplicatesCommandLineProgram.java
- BamToBfqWriter.java
- CheckFingerprint.java
- CollectIndependentReplicateMetrics.java
- CollectJumpingLibraryMetrics.java
- CollectOxoGMetrics.java
- CollectRrbsMetrics.java
- CollectWgsMetricsFromQuerySorted.java
- FingerprintChecker.java
- LiftOverIntervalList.java
- SplitSamByLibrary.java

These classes have to be changed by adding reference sequence call:
```
SamReader in = SamReaderFactory.makeDefault()
            .referenceSequence(REFERENCE_SEQUENCE)
            .open(SamInputResource.of(INPUT));
```

Also, convention calling `referenceSequence` each time SamReader is opened will be needed. 

If those conditions are acceptable, there is no need for the SamReaderFactory changes.

**Comment by yfarjoun** [comment]
I think that this is fine. we might find a better solution later, but for now, this is fine.

**Comment by ZLyanov** [comment]
@yfarjoun Now I'm confused :)   Could you clarify please, what you agreed with:  the changes in this PR or the other approach, described above in the comments by @bmkodoo  & @ekazachkova?

**Comment by yfarjoun** [comment]
I think that it would be better to start with the small changes  to the
tools that need it before making such a big change to the defaults... I
agree with @chrisnorman about needing to make the changes required to read
a cram header.

**Comment by ZLyanov** [comment]
Hi!  Ok, let's summarize the discussion.

First, we still think that using default static reference source in `SamReaderFactory` has some quite important advantages: 

- this approach allows any tool that uses htsjdk not to care about setting reference source each time a reader is opened, 
- it's fully backward compatible and it requires only few lines changed in Picard tools (in `CommandLineProgram` class). 

But if our changes are not acceptable, we'll prepare new changes in Picard tools and htsjdk, as @ekazachkova mentioned above. 

There are two points to consider for these changes:

- We have already published the [PR](https://github.com/broadinstitute/picard/pull/683) that adds CRAM writing support to all relevant metrics. We can update this PR or create a new one, but the majority of the classes in these PRs will intersect. Which way would you prefer: a new PR or updating the existing one?
- Some picard's metrics create readers via htsjdk classes, for instance `DownsampleSam` uses `htsjdk.samtools.DownsamplingIteratorFactory` to open an iterator. So some changes for reference source setting will be required in htsjdk too.

**Comment by lbergelson** [comment]
I'm not a fan of the static defaults.  They can cause big problems in a multiprocess environment like spark.  They also tend to be opaque to the user and don't tend to interact well with other ways of injecting arguments into programs.

**Comment by yfarjoun** [comment]
I think that this PR should be closed at this point since the picard PRs supercede this.

please reopen if I'm mistaken.

**Pull request closed without merging**
